create table [dfeta_initiativecode] (
    [Id] uniqueidentifier not null constraint [EPK[dbo]].[dfeta_initiativecode]]] primary key,
    [SinkCreatedOn] datetime,
    [SinkModifiedOn] datetime,
    [statecode] int,
    [statuscode] int,
    [modifiedby] uniqueidentifier,
    [modifiedby_entitytype] nvarchar(128),
    [modifiedonbehalfby] uniqueidentifier,
    [modifiedonbehalfby_entitytype] nvarchar(128),
    [createdonbehalfby] uniqueidentifier,
    [createdonbehalfby_entitytype] nvarchar(128),
    [organizationid] uniqueidentifier,
    [organizationid_entitytype] nvarchar(128),
    [createdby] uniqueidentifier,
    [createdby_entitytype] nvarchar(128),
    [createdbyyominame] nvarchar(100),
    [organizationidname] nvarchar(100),
    [dfeta_name] nvarchar(450),
    [createdonbehalfbyyominame] nvarchar(100),
    [dfeta_initiativecodeid] uniqueidentifier,
    [modifiedonbehalfbyyominame] nvarchar(100),
    [modifiedbyyominame] nvarchar(100),
    [createdbyname] nvarchar(100),
    [versionnumber] bigint,
    [timezoneruleversionnumber] int,
    [importsequencenumber] int,
    [modifiedonbehalfbyname] nvarchar(100),
    [modifiedbyname] nvarchar(100),
    [modifiedon] datetime,
    [overriddencreatedon] datetime,
    [utcconversiontimezonecode] int,
    [createdonbehalfbyname] nvarchar(100),
    [createdon] datetime,
    [dfeta_value] nvarchar(20)
)
