create table [transactioncurrency] (
    [Id] uniqueidentifier not null constraint [EPK[dbo]].[transactioncurrency]]] primary key,
    [SinkCreatedOn] datetime,
    [SinkModifiedOn] datetime,
    [statecode] int,
    [statuscode] int,
    [organizationid] uniqueidentifier,
    [organizationid_entitytype] nvarchar(128),
    [createdonbehalfby] uniqueidentifier,
    [createdonbehalfby_entitytype] nvarchar(128),
    [modifiedby] uniqueidentifier,
    [modifiedby_entitytype] nvarchar(128),
    [createdby] uniqueidentifier,
    [createdby_entitytype] nvarchar(128),
    [modifiedonbehalfby] uniqueidentifier,
    [modifiedonbehalfby_entitytype] nvarchar(128),
    [currencyprecision] int,
    [modifiedonbehalfbyyominame] nvarchar(100),
    [currencyname] nvarchar(100),
    [versionnumber] bigint,
    [entityimage_timestamp] bigint,
    [modifiedbyyominame] nvarchar(100),
    [createdbyyominame] nvarchar(100),
    [overriddencreatedon] datetime,
    [entityimageid] uniqueidentifier,
    [createdonbehalfbyname] nvarchar(100),
    [uniquedscid] uniqueidentifier,
    [modifiedbyname] nvarchar(100),
    [entityimage_url] nvarchar(200),
    [modifiedon] datetime,
    [createdbyname] nvarchar(100),
    [isocurrencycode] nvarchar(5),
    [createdonbehalfbyyominame] nvarchar(100),
    [transactioncurrencyid] uniqueidentifier,
    [createdon] datetime,
    [exchangerate] decimal(38, 10),
    [importsequencenumber] int,
    [currencysymbol] nvarchar(10),
    [modifiedonbehalfbyname] nvarchar(100)
)
